### ISSUE TITLE
@context steals data from this.context

### ISSUE THREAD

**Issue by michalwerner** [ericclemmons/react-resolver#118]
It seems that `@context` decorator makes pulled data unavailable via `this.context`.

Example:

**index.js**

```
import React from 'react'
import ReactDOM from 'react-dom'
import {ContextProvider, App} from './App'

ReactDOM.render(
  <ContextProvider>
    <App />
  </ContextProvider>,
  document.getElementById('root')
)
```

**app.js**

```
import React, { Component } from 'react'
import {context} from 'react-resolver'

class ContextProvider extends Component {
  getChildContext() {
    return { test: 'testing'}
  }
  render() {
    return <div>{this.props.children}</div>
  }
}
ContextProvider.childContextTypes = {
  test: React.PropTypes.string.isRequired,
}

@context('test')
class App extends Component {
  render() {
    return (
      <div>
        from props: {this.props.test}<br />
        from context: {this.context.test}
      </div>
    )
  }
}
App.contextTypes = {
  test: React.PropTypes.string.isRequired,
}

export {ContextProvider, App}
```

in this case output will be:

```
from props: testing
from context:
```

Is this intended behavior? **Is is possible to have access to context data via `this.context` when they're also used with `@context`?**

Of course this example doesn't make much sense because I've used `@context` for nothing, but let's say I want to use this decorator only for feeding `@resolve` with some context data and still have access to them in component, in a standard way.

**Comment by michalwerner** [comment]
Also I've just realized it doesn't happen with ES5/ES6 syntax.

**Comment by monder** [comment]
Yes, it is expected because thats how decorators work. The same is for `@resolve`, `@client`, etc.

It may not be obvious, but when you write
```js
@context('test')
class App extends ...
```
Variable `App` holds the `ContextDecorator` and not the `App` class. Thus  in`App.contextTypes = ` you assign it to ContextDecorator (which BTW already has it), but the `App` class remains without `contextTypes` or `propTypes`.

I suggest to use class statics (ES7) if you want to use decorators.
Or its possible 
If you don't want to use class statics (ES7), then as I workaround you should create a class and add decorator to it in two steps:
```js
class App extends Component {...}
App.contextTypes = {...}
// The App is the actual class, so you can assign any properties you like
App = context('test')(App);
// The App is now a decorator wrapper with the class inside
```

**Comment by monder** [comment]
Also, a note:

I usually separate "pure" classes and their data loading logic. So that in tests I can load pure versions without any "resolvers" so I can test it offline with mocked data passed directly)

```js
export class App extends React.Component {
  static propTypes = {
    // props I expect from both: api and the resolver.
  }
} // pure


@context(...)
@resolve(...)
export default class extends App {} // Add a prop to existing class
```
The "pure" class is exported as `App` and the class with loader is exported as `default` (with no class name, but you can put whatever).

Or sometimes even spit it in two separate files.

**Comment by ericclemmons** [comment]
`@context` was really just a terse way of getting access to `router` for me.  If you're familiar with the context API and comfortable configuring it, then there's no need to use `@context`.

I was just lazy ;)  (And it makes functional components prettier)

**Comment by michalwerner** [comment]
Thanks, that clears much!

**Comment by ericclemmons** [comment]
@michalwerner Glad we could help!  Context is tricky as it is :D
