### ISSUE TITLE
React resolver usage with nested components

### ISSUE THREAD

**Issue by bizmurr** [ericclemmons/react-resolver#12]
This seems pretty cool, but I am still a little unclear as to how to best utilize this.

If I have route that is something like:

```xml
<Route name='user' path='/user/:username/?' handler={UserView}>
   <DefaultRoute handler={UserAboutSubview} />
   <Route name='user-activity' path='activity/?' handler={UserActivitySubview} />
   <Route name='user-favorites' path='favs/?' handler={UserFavsSubview} />
</Route>
```

Normally, I would think:

- `UserView`, calls an `action` to initialize the `UsersStore`, on `componentDidMount`, and then `setState` upon `store update`. Then pass the `state` as `props` to `UserAboutSubview`, and then listen to any changes on `UsersStore`.

But if you use `react-resolver`, would you would still initialize the the `UsersStore`, at `UserView`, and then instead of passing down props, the `Subviews`, fetch the data from the store?

How would updates from the `UsersStore` be propagated?

**Comment by ericclemmons** [comment]
First, thanks for opening an issue!

Your assumptions on classic-React data-fetching and how to do it with `react-resolver` are correct.

- Most data-fetching that you would've done in `componentDidMount` can now be placed in `statics: { resolve: { ... } }` as sync functions with a `return`, or async by calling `done` or returning a Promise.

- Using this project, **your parents should no longer have to worry about cascading data down as `props` to children**.  Instead, each component should request the exact data it needs from a Store or service.

- The functions in your `statics: { resolve: { ... } }` object are scoped to the component's `this` instance, which means you can use `this.getParams().username` in all of your sub-handlers.

So, assuming _every one of your handlers will utilize user data in some way_, I'd do the following:

- `UserView` has something like:

```
statics: {
  resolve: {
    user: function() {
      // Fetch the current user & cache it in the store to avoid subsequent requests
      return UserStore.fetch({ name: this.getParams().username }); // Promise
    }
  }
}
```

- `UserAboutSubView`, and any other  will then be able to request this data synchronously via:

```
statics: {
  resolve: {
    user: function() {
      return UserStore.getCurrent();
    }
  }
}
```

So, the final question is:
> "How would updates from the `UsersStore` be propagated?"

I'd imagine 2 ways:

1. When the route changes and the `UserView` handler again and all of the `resolve` objects are re-ran.
2. If changes are expected, since `props` should be _idempotent_, you'd want the parent-most component `UserView` to re-render based on `this.state.user`, causing the try to be re-rendered with new props & calls to `UserStore.getCurrent();`

It's clear I should put up a more complex demo to answer these with code for yourself & others.  The complexity I've found with doing things this way is **writing components so that they're not coupled with data being fetched by other components**.

**Comment by bizmurr** [comment]
Thanks for the quick response! This is starting to make more sense. I'm really liking the sound of this.

For the the last question about propagating store changes, could you give a little it of more detail as to what you mean by 2?

So, if I'm understanding correctly, I would add a `listener` on `componentWillMount`, for changes on the `store` and then that will update the `state`, cause a `rerender`, and triggering that `rerender` should cause all the `children` to call `UsersStore.getCurrent()`, correct?

Definitely, I think a demo would be greatly appreciated. If you could provide an example on testing too, that would also be awesome! I guess you would just mock out the call that `resolve` makes?

**Comment by ericclemmons** [comment]
That's correct, the re-rendering of the `children` should each call `UsersStore.getCurrent()` again.  If not, well, I guess we have a bug on our hands, don't we? ;)

This project was actually created to make testing easier!

Tests should be able to mock `user` like crazy, and keep testing the result of `<UserActivitySubview user={someMockUser} />`.  The only difference is, when rendering with real data, the `user` prop is injected dynamically, and consistent with testing!  (Heck, you can even mock out the `UserStore.getCurrent()` to return `someMockUser`, and test against `Resolver.resolve(<UserActivitySubview />)` , but that's too much coupling IMO.)

**Comment by bizmurr** [comment]
Awesome, thanks for the insight! :bow:

**Comment by ericclemmons** [comment]
@bizmurr Glad to have helped!  I hope to see you in http://reactiflux.com/ if you aren't there already!
