### ISSUE TITLE
Idea: Provide a dependency-less build

### ISSUE THREAD

**Issue by goatslacker** [ericclemmons/react-resolver#15]
I believe there is value in keeping bluebird, however if you're running in an ES6-shimmed environment then you already having promises support making bluebird redundant. It would be great to provide a build that has no dependencies this way you get a minimal react-resolver.

**Comment by jesseskinner** [comment]
+1

**Comment by mattmccray** [comment]
:+1: 

As an experiment I ran react-resolver through browserify to see if I could using it with my build env... Not so much, the result was 1.1mb, and ~300kb after uglify.

**Comment by ericclemmons** [comment]
@goatslacker Good idea!  Any preference on how this should be implemented?

- Always assume the existence of `Promise`, leaving it to the consumer to define. (No idea how this works for testing, but we'll see!)
- Use getify's [native-promise-only][1] which polyfills `Promise` IFF it doesn't exist (~2k dependency)

The other problem is that `react-resolver` has a peer dependency on both `react` and `react-resolver`.  I bet the bloat you saw is more than just Bluebird.

@mattmccray What script did you run as an "experiment?" I'd <3 to re-use this for testing, since this library should really be ~1k gzipped.

[1]: https://github.com/getify/native-promise-only

**Comment by mattmccray** [comment]
I didn't have a ton of time to look into it, so it was _very_ naive. Basically I just added `browserify` and `babelify` as dev-deps and added this to the npm scripts:

`"build-browser": "NODE_ENV=production browserify src/index.js -t babelify --outfile dist/react-resolver.js --standalone ReactResolver",`

Clearly more is going to be required than this.

You're right. Between including react, react-router, bluebird, and lodash the output got pretty big.

**Comment by goatslacker** [comment]
I'd keep bluebird in as the default and then provide a separate path for commonjs require that doesn't run through bluebird.

**Comment by mattmccray** [comment]
For `react`, and `react-router` -- If you want to use browserify to build the standalone version -- you could use [browserify-global-shim](https://www.npmjs.com/package/browserify-global-shim).

What doese bluebird add to the output? ~40kb?

**Comment by ericclemmons** [comment]
@mattmccray 23.2k
> https://cdn.jsdelivr.net/bluebird/latest/bluebird.min.js

**Comment by ericclemmons** [comment]
I'll probably check out how `react-router` bundles for Browser/standalone, since React shouldn't be a hard requirement there.

What I'm thinking is that, maybe it's simply telling the build to _ignore_ `require('react')` and `require('react-router')`.  Those deps would be necessary in the client code & would work when bundling in your app, but wouldn't bloat the file size at all...

**Comment by mattmccray** [comment]
> What I'm thinking is that, maybe it's simply telling the build to ignore require('react') and require('react-router'). Those deps would be necessary in the client code & would work when bundling in your app, but wouldn't bloat the file size at all...

Perhaps... Depends on if it's being used in a commonjs env. If not, it'd need to be pulled from globals.

**Comment by ericclemmons** [comment]
@mattmccray I don't know _anyone_ who'd be using these things outside of a CommonJS env :D

Seriously, interesting point to consider though.  I may end up with multiple build targets as a result, but it seems like that's the _best_ thing to do...supporting Browser + Node, I mean.

**Comment by goatslacker** [comment]
:+1: to that idea

**Comment by mattmccray** [comment]
@ericclemmons :)

The project I'm working on uses [brunch](http://brunch.io) for building. Technically it IS a CommonJS env, but not via NPM. It uses bower (alas and alack) for dependency management. So it wouldn't resolve `require( 'react')` to anything.

**Comment by moretti** [comment]
I really like Bluebird, but I think that this project should use promises in a way that is totally compatible with ES6, so that we can easily swap it out in the build process:

with browserify:
```
browserify --require bluebird:./path/to/Promise main.js
```
with webpack:
```
module.exports = {
  // ...
  resolve: {
    alias: {
      'bluebird': '../path/to/Promise'
    }
  }
};
```
We can also reduce the size of this library by not requiring the entire `lodash` library:
```
import _ from 'lodash';
// ...
if (_.isFunction(value)) {
// ...

```
can be refactored to:
```
import isFunction from 'lodash/lang/isFunction'
// ...
if (isFunction(value)) {
// ...
```

**Comment by ericclemmons** [comment]
No dependencies in  [v1.0.0](d7c9d843e091700f0c3f61843f8f3e8bfd707f64).

**Comment by goatslacker** [comment]
Link is dead

**Comment by ericclemmons** [comment]
Eh, stupid Github linked it as an issue for some reason.
> https://github.com/ericclemmons/react-resolver
