### ISSUE TITLE
Use statics and decorators

### ISSUE THREAD

**Issue by srph** [ericclemmons/react-resolver#53]
Somehow, this is preferable:

```jsx
@resolve
class SomeComponent extends React.Component {
  static resolve = {
    user() => {
    }
  };
}
```

**Comment by ericclemmons** [comment]
@srph How do like that compared to...
> https://github.com/ericclemmons/react-resolver/blob/6145ce4a85c0e8af78685d47d616dcef8104d50a/examples/react-router/components/Stargazers.js#L6-L10
?

While working on v2 internally, I oped out of a static property since _props cascade_ with each `@resolve`, which made it easier to do things like:

1. `@resolve("user", function({ params } { ... })`
2. `@resolve("form", function({ user }) { ... })`
3. `class EditUser { ... render() { const { user, form } = this.props; ... }`

**Comment by srph** [comment]
Just a stupid question: isn't that going to be a little too nested (in the hierarchy)?

**Comment by ericclemmons** [comment]
@srph Internally, they're converted to normal Object-syntax:

```js
@resolve({
  user: function(...) { ... },
  ...
})
```

So you can opt for a more concise structure.  Having used this for ~6 months, I've been opting for individual `@resolve` statements so I can have explicit orders but **resolving an object is more performant**, as the resolver will resolve 1 level's props at a time.

In short, @srph objects are probably best :)

**Comment by srph** [comment]
Ah, I see. I get it. Also, we can get resolved objects through props, right? Pretty cool.

I just checked the source code (and still checking). How do you run two promises at the same time with this decorator? For example, we got 3 promises, `auth`, `friends`, and `posts`.

`auth` start -> `auth` end -> `friends` start -> `posts` start -> `friends` / `posts` end -> `friends` / `posts` end

I don't see this happening in a real world scenario (I only use resolves for accessing a certain resource; this way I can validate if the resource exists). I'll try to elaborate more if my example is a bit confusing (or if it doesn't make sense) :smile:

**Comment by ericclemmons** [comment]
Looks like you edited your question :)

First, yes.  Suppose you have something like:

```js
render() {
  return (
    <div>
      <AsyncOne />
      <AsyncTwo />
      <AsyncThree />
    </div>
  );
}
```

All 3 of those children will fire off their promises at once since they're siblings and not dependent on each other.

_Within_ each of those, you can `@resolve({ ... })` an entire object at once, or `@resolve(first)` and `@resolve(second)` if `second` is dependent on the value of `first`.

**Comment by srph** [comment]
Awesome! Though, I'm not sure where we're heading for v2. I'd like to help out where I can.
