### ISSUE TITLE
Access the component not just the properties

### ISSUE THREAD

**Issue by ccerrato147** [ericclemmons/react-resolver#91]
In all the examples I've seen so far the only object that can be access is the "properties" object collection of the component that's being resolved. For example:

export default resolve("users", function(properties) {
//your code
})(MyComponent);

How can I access the component instance to which the properties belong to?

For example:

export default resolve("users", function(componentInstance) {
 let someVariable = componentInstance.state.something;
})(MyComponent);

The thing is that I would like to access the state or functions of the component instance not just the properties.

Is this possible in react-resolver?

**Comment by ericclemmons** [comment]
Oh, no, The `@resolve` creates a HoC (higher-order component) _around_ your original component.

The `props` in `@resolve(prop, function(props)` are the _passed in `props` from the parent/owner:

```js
@resolve("user", function(props) { return user.load(props.userId); })
class UserProfile ...
```

```jsx
<UserProfile userId={1} />
```

The goal is:

- Your components don't have to worry about async data-fetching.
- `@resolve` will lookup the data your component needs (e.g. `user`) from passed in props (e.g. `userId`).
- `@resolve` is skipped if you already provide the resolved value (e.g. `user`), so that testing doesn't require any async loading.

Besides, the _component instance_ doesn't exist until `@resolve` finishes & renders the component.

I hope that helps!

**Comment by ccerrato147** [comment]
Thank you Eric. This is exactly what I thought was the case. Just wanted to make sure.

By the way, cool project!
